title: Brett Phinney
description: "Director, UC Davis Proteomics Core | Darth Data"
url: "https://bsphinney.github.io"
baseurl: ""
theme: null
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
